name = "CA_Notebooks"
uuid = "efbb3074-70da-4743-88a3-d33b2acf9220"
authors = ["Hayden Free <hayden.free@uky.edu>"]
version = "0.1.0"

[deps]
CurricularAnalytics = "593ffa3d-269e-5d81-88bc-c3b6809c35a6"
CurricularVisualization = "fbaee398-1ac9-4ee2-a69c-ef17203eefbf"
